### ISSUE TITLE
High CPU consumption after launching

### ISSUE THREAD

**Issue by ghost** [mauritiusdadd/lxnstack#11]
Kubuntu 15.04 x86_64, lxnstack installed from here: http://sourceforge.net/projects/lxnstack/files/binary%20packages/lxnstack-1.4.4.deb/download
Application successfully starts but starts consuming 100% on one of the CPU cores. Also, if the app is in the focus X process consumes around 25-35% from another CPU core.

**Comment by mauritiusdadd** [comment]
Yes, it's a known issue, but it should be solved in 1.5.0... can you confirm this?

**Comment by ghost** [comment]
Yes, it is indeed solved
