### ISSUE TITLE
lxnstack 1.5.0 doesn't launch

### ISSUE THREAD

**Issue by ghost** [mauritiusdadd/lxnstack#12]
Kubuntu 15.04 x86_64. When trying to start the application it fails with this error:

"No handlers could be found for logger "lxnstack-root-logger"  
QWidget: Must construct a QApplication before a QPaintDevice  
Aborted (core dumped)"

**Comment by mauritiusdadd** [comment]
Probably you are missing one or more python2 packages needed by the program. However an error message telling wich package is missing should have been displayed. Can you confirm that the message is displayed using the following commit: https://github.com/mauritiusdadd/lxnstack/commit/b83b4f6c35af6b5c8df8683702ef143d600147ff ?

**Comment by ghost** [comment]
This commit helped lxnstack to launch and report that I was missing python bindings for opencv. Now it works fine, time for some staking :-)

**Comment by mauritiusdadd** [comment]
Glad to hear that it worked, and than you for reporting the issue :)
