### ISSUE TITLE
AttributeError?

### ISSUE THREAD

**Issue by darethehair** [mauritiusdadd/lxnstack#14]
Hello!  Just trying out the current version of lxnstack from Github, and after installing it (and all dependencies) I get an error:

```
darren@frodo2 /ldat1/stacking/astro $ lxnstack
FITS support enabled
CR2 support enabled
FOUND LIBV42
[WARNING] 2016-09-30 09:13:50,791 - <lxnstack.utils module>.getQIcon - No icon found for: "None"
[WARNING] 2016-09-30 09:13:50,838 - <lxnstack.utils module>.getQIcon - No icon found for: "export-calibrated"
[WARNING] 2016-09-30 09:13:50,891 - <lxnstack.utils module>.getQIcon - No icon found for: "generate-transf-table"
[WARNING] 2016-09-30 09:13:50,906 - <lxnstack.utils module>.getQIcon - No icon found for: "load-transf-table"
[WARNING] 2016-09-30 09:13:50,918 - <lxnstack.utils module>.getQIcon - No icon found for: "save-transf-table"
[WARNING] 2016-09-30 09:13:50,919 - <lxnstack.utils module>.getQIcon - No icon found for: "save-transf-table"
[WARNING] 2016-09-30 09:13:50,949 - <lxnstack.utils module>.getQIcon - No icon found for: "channel-mapping"
[WARNING] 2016-09-30 09:13:51,007 - <lxnstack.utils module>.getQIcon - No icon found for: "video.scheduler"
[WARNING] 2016-09-30 09:13:51,018 - <lxnstack.utils module>.getQIcon - No icon found for: "video-single-shot"
[WARNING] 2016-09-30 09:13:51,092 - <lxnstack.utils module>.getQIcon - No icon found for: "type-video-file"
[WARNING] 2016-09-30 09:13:51,104 - <lxnstack.utils module>.getQIcon - No icon found for: "type-frame-sequence"
[WARNING] 2016-09-30 09:13:51,245 - <lxnstack.videocapture.V4l2VideoDevice object at 0x7fd842665b98>.open - Cropping not supported
[ERROR] 2016-09-30 09:13:51,298 - <lxnstack.videocapture.V4l2VideoDevice object at 0x7fd842665b98>._enumerate_menu - Error 22: Invalid argument
[ERROR] 2016-09-30 09:13:51,300 - <lxnstack.videocapture.V4l2VideoDevice object at 0x7fd842665b98>._enumerate_menu - Error 22: Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/lxnstack", line 182, in <module>
    mainApp = lxnstack.main_app.theApp(lang, args)
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/main_app.py", line 396, in __init__
    self.updateCaptureDevicesList()
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/main_app.py", line 773, in updateCaptureDevicesList
    self.devices = tuple(videocapture.listVideoDevices())
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 40, in listVideoDevices
    vd_list += _list_cv2_devices()
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 3655, in _list_cv2_devices
    if not vd.open(dev):
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 2179, in open
    self._build_ui_controls_interface()
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 224, in _build_ui_controls_interface
    self._qt_build_ui_controls_interface()
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 2352, in _qt_build_ui_controls_interface
    self._qt_ui_helper_update_framerates(fps_menu)
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 2240, in _qt_ui_helper_update_framerates
    cidx = fps_menu.findData(QtCore.QVariant(int(self.getFrameRate())))
  File "/usr/local/lib/python2.7/dist-packages/lxnstack/videocapture.py", line 2576, in getFrameRate
    val = self._device.get(cv2.CAP_PROP_FPS)
AttributeError: 'module' object has no attribute 'CAP_PROP_FPS'
```

Have I done something wrong?

**Comment by mauritiusdadd** [comment]
Hi, what version of opencv are you using? The current version of lxnstack works only with opencv >= 3.1.0

You can check the opencv version using the following command

```
$ python2 -c "import cv2; print(cv2.__version__)"
3.1.0
```

**Comment by darethehair** [comment]
With normal Debian repositories running with Linux Mint LMDE:

```
$ python2 -c "import cv2; print(cv2.__version__)"
2.4.9.1
```

I could not find any OpenCV deb files for 3.1.0+, so I was forced (?) to compile from source using a rather scary script that did a lot of stuff and used a lot of temporary work space:

[(http://milq.github.io/install-opencv-ubuntu-debian/)]

Even then, there was a missing component that I required before I had a clean compile i.e. 'QtOpenGL' was missing, so:

`sudo apt-get install libqt5opengl5 libqt5opengl5-dev`

Ultimately this got me to a working level of OpenCV:

```
python2 -c "import cv2; print(cv2.__version__)"
3.1.0
```

All in all, I was surprised at how much effort it (seemingly) required to get the newest version of OpenCV -- well beyond what a newbie would be able to handle (I think).  Did you also have to compile from source?  Did LxnStack need some extra functionality that version 2.4.9.1 did not provide?

I was able to start LxnStack, but now (I guess) I need some tutorials.  All I have ever used is 'Deep Sky Stacker'.  Do you think that LxnStack will provide the same easy functionality to me, without the crazy need to boot Windows just to use it?

**Comment by mauritiusdadd** [comment]
> I could not find any OpenCV deb files for 3.1.0+, so I was forced (?) to compile from source using a rather scary script 

The last commit compatible with opencv 2.4.9 is the following (and I suggest you to use it instead of using a version of opencv that is still not supported by your distribution) : 39bb528438a0d6d12b38fefe0f5b8254d0fcbaee 

> I was surprised at how much effort it (seemingly) required to get the newest version of OpenCV -- well beyond what a newbie would be able to handle (I think)

Well, I can understand you, but git sources are not intended to be used as the main way to install a program and you should be prepared to build a lot of external dependencies in order to get it work... that's why there's a release system (and don't think newbies use git sources anyway ;) )

> Did you also have to compile from source?

No, I didn't. I just use what is in the standard Arch Linux repositories.

> Did LxnStack need some extra functionality that version 2.4.9.1 did not provide?

No, it didn't. As above, I just use what is in the standard Arch Linux repositories.

> I was able to start LxnStack, but now (I guess) I need some tutorials

Yeah, unfortunately there is no tutorial available at the moment: I develop this program in my free time (and lately I have been quite busy) and I never finished to update/write the documentation. My bad.

> All I have ever used is 'Deep Sky Stacker'. Do you think that LxnStack will provide the same easy functionality to me

I'm sorry, but I can't answer to this question: I never used any stacking program on Windows so I really don't know what functionalities DSS provides.

Since this is not an actual bug with the code I'm going to close this issue, but feel free to open another one in case you find something that does not work.
